# Site settings
title: C:\Temp
email: antiinternet@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  No description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
github_username:  Regentag

# Build settings
markdown: redcarpet
redcarpet:
  extensions: [
    "no_intra_emphasis",
    "fenced_code_blocks",
    "autolink",
    "strikethrough",
    "superscript"
  ]


highlighter: pygments

permalink: pretty
